{
 "title": "Containerized windows exporter metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TX (sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{nic = \"Intel[R] Wireless-AC 9260 160MHz\"}[2m])  * 8 /1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Memory's usage running in docker container",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - windows_memory_available_bytes / windows_memory_physical_total_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "containerized docker disk usage",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1- (windows_logical_disk_free_bytes{volume = \"C:\"} /windows_logical_disk_size_bytes{volume = \"C:\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avgerage CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg  by (instance) (rate(windows_cpu_time_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX(download) Mbp",
   "type": "timeseries",
   "description": "Calculates the per-second average rate of increase of the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. Also, the calculation extrapolates to the ends of the time range, allowing for missed scrapes or imperfect alignment of scrape cycles with the range's time period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{nic = \"Intel[R] Wireless-AC 9260 160MHz\"}[2m])  * 8 /1e6",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{instance= \"host.docker.internal:9182\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - windows_memory_available_bytes / windows_memory_physical_total_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "cpu usage inside a docker container. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "100 * (1 - (rate(windows_cpu_time_total{mode=\"idle\"}[5m])))",
     "legendFormat": "Core {{core}}"
    }
   ]
  }
 ]
}